name: flaggio-cleaner-bot
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: "golang:1.14"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run tests
        run: make test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: "golangci/golangci-lint:latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint
        run: golangci-lint run --timeout 5m0s
  build:
    name: Build
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.uw.systems
          repository: uw/flaggio-cleaner-bot
          tag_with_ref: true
          tags: ${{ github.sha }}
